# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/user/Downloads/GitHubProjects/telo2/ui/agent.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 665)
        MainWindow.setStyleSheet("QWidget{\n"
"font: 57 8pt \"Yu Gothic Medium\";\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"\n"
"QTableWidget {\n"
"border:none;\n"
"background-color: white; \n"
"alternate-background-color: #f0f0f0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(18, 65, 141);            \n"
"    color: rgb(243, 249, 254);\n"
"    font: 57 8pt \"Yu Gothic Medium\";\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(24, 89, 193); \n"
"}\n"
"\n"
"#QTableWidget QTableCornerButton::section {\n"
"    background-color: #74b9ff; /* Top-left corner color */\n"
"    border: 1px solid #0984e3;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #dfe6e9;  /* Background color of the scrollbar track */\n"
"    height: 12px;  /* Thickness of the scrollbar */\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #0984e3; /* Color of the scrollbar handle (slider) */\n"
"    min-width: 20px; /* Minimum width of the handle */\n"
"    border-radius: 6px; /* Rounded edges */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #74b9ff; /* Lighter color when hovered */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Removes the small arrow buttons */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none; /* Keeps empty space color same */\n"
"}\n"
"\n"
"QListWidget{\n"
"    border: 1px solid rgb(161, 161, 161);    \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid rgb(18, 65, 141);    \n"
"    border-radius: 9px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("background-color: rgb(8, 123, 225);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logoLabel = QtWidgets.QLabel(self.widget)
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("/Users/user/Downloads/GitHubProjects/telo2/ui/../Downloads/travel-agency (2).png"))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout.addWidget(self.logoLabel)
        self.homeBtn = QtWidgets.QPushButton(self.widget)
        self.homeBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"border-radius: 0px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid #74b9ff;\n"
"}")
        self.homeBtn.setObjectName("homeBtn")
        self.verticalLayout.addWidget(self.homeBtn)
        self.reservationsBtn = QtWidgets.QPushButton(self.widget)
        self.reservationsBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"border-radius: 0px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid #74b9ff;\n"
"}")
        self.reservationsBtn.setObjectName("reservationsBtn")
        self.verticalLayout.addWidget(self.reservationsBtn)
        self.staffBtn = QtWidgets.QPushButton(self.widget)
        self.staffBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"border-radius: 0px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid #74b9ff;\n"
"}")
        self.staffBtn.setObjectName("staffBtn")
        self.verticalLayout.addWidget(self.staffBtn)
        self.vehiclesBtn = QtWidgets.QPushButton(self.widget)
        self.vehiclesBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"border-radius: 0px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid #74b9ff;\n"
"}")
        self.vehiclesBtn.setObjectName("vehiclesBtn")
        self.verticalLayout.addWidget(self.vehiclesBtn)
        self.statsBtn = QtWidgets.QPushButton(self.widget)
        self.statsBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"border-radius: 0px;\n"
"background-color: rgb(8, 123, 225);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid #74b9ff;\n"
"}")
        self.statsBtn.setObjectName("statsBtn")
        self.verticalLayout.addWidget(self.statsBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.logOutBtn = QtWidgets.QPushButton(self.widget)
        self.logOutBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"/*\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"background-color: rgb(233, 128, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgb(240, 168, 0);\n"
"}\n"
"*/")
        self.logOutBtn.setObjectName("logOutBtn")
        self.verticalLayout.addWidget(self.logOutBtn)
        self.horizontalLayout.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.stackedWidget.setAcceptDrops(False)
        self.stackedWidget.setStyleSheet("background-color: rgb(243, 249, 254);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.gridLayout = QtWidgets.QGridLayout(self.homePage)
        self.gridLayout.setObjectName("gridLayout")
        self.tourTableWidget = QtWidgets.QTableWidget(self.homePage)
        self.tourTableWidget.setStyleSheet("")
        self.tourTableWidget.setCornerButtonEnabled(True)
        self.tourTableWidget.setObjectName("tourTableWidget")
        self.tourTableWidget.setColumnCount(9)
        self.tourTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tourTableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout.addWidget(self.tourTableWidget, 1, 0, 1, 3)
        self.createTourDescriptionBtn = QtWidgets.QPushButton(self.homePage)
        self.createTourDescriptionBtn.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"background-color:#74b9ff;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(136, 205, 255);\n"
"}")
        self.createTourDescriptionBtn.setObjectName("createTourDescriptionBtn")
        self.gridLayout.addWidget(self.createTourDescriptionBtn, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.homePage)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 3)
        self.stackedWidget.addWidget(self.homePage)
        self.reservationsPage = QtWidgets.QWidget()
        self.reservationsPage.setObjectName("reservationsPage")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.reservationsPage)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.reservationsPage)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.reservationsPage)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.lineEdit = QtWidgets.QLineEdit(self.reservationsPage)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.add_Reservation_Button = QtWidgets.QPushButton(self.reservationsPage)
        self.add_Reservation_Button.setStyleSheet("QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 14px;\n"
"padding: 5px;\n"
"background-color: rgb(8, 123, 225);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}")
        self.add_Reservation_Button.setObjectName("add_Reservation_Button")
        self.verticalLayout_2.addWidget(self.add_Reservation_Button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.reservationsPage)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.widget_3 = QtWidgets.QWidget(self.reservationsPage)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.widget_4 = QtWidgets.QWidget(self.reservationsPage)
        self.widget_4.setMinimumSize(QtCore.QSize(246, 32))
        self.widget_4.setMaximumSize(QtCore.QSize(246, 32))
        self.widget_4.setStyleSheet("border: 1px solid rgb(161, 161, 161);    \n"
"    border-radius:10px;")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setStyleSheet("border:none;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.horizontalLayout_4.setStretch(0, 4)
        self.horizontalLayout_4.setStretch(1, 6)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.horizontalLayout_3.setStretch(0, 6)
        self.horizontalLayout_3.setStretch(1, 4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.stackedWidget.addWidget(self.reservationsPage)
        self.staffPage = QtWidgets.QWidget()
        self.staffPage.setObjectName("staffPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.staffPage)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.staffPage)
        self.tabWidget.setStyleSheet("QTabBar{\n"
"border:none;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"        background: rgb(220, 228, 231);\n"
"        \n"
"       \n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        background: #087be1;\n"
"        color: white; \n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background: #2f8ee4;\n"
"        color: white; \n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.travelagentTableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.travelagentTableWidget.setStyleSheet("")
        self.travelagentTableWidget.setObjectName("travelagentTableWidget")
        self.travelagentTableWidget.setColumnCount(8)
        self.travelagentTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.travelagentTableWidget.setHorizontalHeaderItem(7, item)
        self.gridLayout_3.addWidget(self.travelagentTableWidget, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.widget_2 = QtWidgets.QWidget()
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.teamleaderTableWidget = QtWidgets.QTableWidget(self.widget_2)
        self.teamleaderTableWidget.setStyleSheet("")
        self.teamleaderTableWidget.setObjectName("teamleaderTableWidget")
        self.teamleaderTableWidget.setColumnCount(5)
        self.teamleaderTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.teamleaderTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamleaderTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamleaderTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamleaderTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.teamleaderTableWidget.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.teamleaderTableWidget, 0, 0, 1, 2)
        self.tabWidget.addTab(self.widget_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.driverTableWidget = QtWidgets.QTableWidget(self.tab)
        self.driverTableWidget.setObjectName("driverTableWidget")
        self.driverTableWidget.setColumnCount(6)
        self.driverTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.driverTableWidget.setHorizontalHeaderItem(5, item)
        self.gridLayout_5.addWidget(self.driverTableWidget, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.staffPage)
        self.vehiclePage = QtWidgets.QWidget()
        self.vehiclePage.setObjectName("vehiclePage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.vehiclePage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.busesTableWidget = QtWidgets.QTableWidget(self.vehiclePage)
        self.busesTableWidget.setObjectName("busesTableWidget")
        self.busesTableWidget.setColumnCount(9)
        self.busesTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.busesTableWidget.setHorizontalHeaderItem(8, item)
        self.gridLayout_6.addWidget(self.busesTableWidget, 0, 0, 1, 2)
        self.stackedWidget.addWidget(self.vehiclePage)
        self.statsPage = QtWidgets.QWidget()
        self.statsPage.setObjectName("statsPage")
        self.label_3 = QtWidgets.QLabel(self.statsPage)
        self.label_3.setGeometry(QtCore.QRect(280, 270, 201, 81))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.statsPage)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 8)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeBtn.setText(_translate("MainWindow", "Tours"))
        self.reservationsBtn.setText(_translate("MainWindow", "Reservations"))
        self.staffBtn.setText(_translate("MainWindow", "Staff"))
        self.vehiclesBtn.setText(_translate("MainWindow", "Vehicles"))
        self.statsBtn.setText(_translate("MainWindow", "Stats"))
        self.logOutBtn.setText(_translate("MainWindow", "Log Out"))
        item = self.tourTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tourTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.tourTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Starting Date"))
        item = self.tourTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "End Date"))
        item = self.tourTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Description"))
        item = self.tourTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Distance"))
        item = self.tourTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Agent"))
        item = self.tourTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Transportation"))
        item = self.tourTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Status"))
        self.createTourDescriptionBtn.setText(_translate("MainWindow", "Create Tour Description 📝"))
        self.label_2.setText(_translate("MainWindow", "Tours"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Scheduled Tours</p></body></html>"))
        self.add_Reservation_Button.setText(_translate("MainWindow", "Create Reservation"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Number Of People"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hotel"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cost"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Payment Type"))
        self.label_4.setText(_translate("MainWindow", "Total Cost:"))
        self.label_5.setText(_translate("MainWindow", "--"))
        item = self.travelagentTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.travelagentTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Usename"))
        item = self.travelagentTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.travelagentTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.travelagentTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.travelagentTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Role"))
        item = self.travelagentTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Hours"))
        item = self.travelagentTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Salary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Travel Agents"))
        item = self.teamleaderTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.teamleaderTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.teamleaderTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.teamleaderTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Payment"))
        item = self.teamleaderTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Skills"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget_2), _translate("MainWindow", "Team Leaders"))
        item = self.driverTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tax Code"))
        item = self.driverTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.driverTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.driverTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type"))
        item = self.driverTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Salary"))
        item = self.driverTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Drivers"))
        item = self.busesTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Plate Number"))
        item = self.busesTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Model"))
        item = self.busesTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Year"))
        item = self.busesTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Mileage"))
        item = self.busesTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.busesTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "RentalCost"))
        item = self.busesTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Seats"))
        item = self.busesTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Status"))
        item = self.busesTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Contract Date"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">STATS TO DO!!</span></p></body></html>"))
