# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/user/Downloads/GitHubProjects/telo2/ui/reservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 665)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(18, 65, 141);\n"
"    border-radius: 6px;\n"
"    alternate-background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"    color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(18, 65, 141);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"QTableWidget {\n"
"border:none;\n"
"background-color: white; \n"
"alternate-background-color: #f0f0f0;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgb(18, 65, 141);            \n"
"    color: rgb(243, 249, 254);\n"
"    font: 57 8pt \"Yu Gothic Medium\";\n"
"    padding: 5px;\n"
"    border: 1px solid rgb(24, 89, 193); \n"
"}\n"
"\n"
"#QTableWidget QTableCornerButton::section {\n"
"    background-color: #74b9ff; /* Top-left corner color */\n"
"    border: 1px solid #0984e3;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #dfe6e9;  /* Background color of the scrollbar track */\n"
"    height: 12px;  /* Thickness of the scrollbar */\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #0984e3; /* Color of the scrollbar handle (slider) */\n"
"    min-width: 20px; /* Minimum width of the handle */\n"
"    border-radius: 6px; /* Rounded edges */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #74b9ff; /* Lighter color when hovered */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    background: none; /* Removes the small arrow buttons */\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none; /* Keeps empty space color same */\n"
"}\n"
"\n"
"QListWidget{\n"
"    border: 1px solid rgb(161, 161, 161);    \n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid rgb(18, 65, 141);    \n"
"    border-radius: 9px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(18, 65, 141);\n"
"    border-radius: 6px;\n"
"    alternate-background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"    color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(18, 65, 141);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.reservationTab = QtWidgets.QWidget()
        self.reservationTab.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(18, 65, 141);\n"
"    border-radius: 6px;\n"
"    alternate-background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"    color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(18, 65, 141);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.reservationTab.setObjectName("reservationTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.reservationTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(122, 49, 531, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Tourslabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Tourslabel.setObjectName("Tourslabel")
        self.verticalLayout_2.addWidget(self.Tourslabel)
        self.Tour_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.Tour_listWidget.setObjectName("Tour_listWidget")
        self.verticalLayout_2.addWidget(self.Tour_listWidget)
        self.TourslineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.TourslineEdit.setObjectName("TourslineEdit")
        self.verticalLayout_2.addWidget(self.TourslineEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Clientlabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Clientlabel.setObjectName("Clientlabel")
        self.verticalLayout.addWidget(self.Clientlabel)
        self.Client_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.Client_listWidget.setStyleSheet("")
        self.Client_listWidget.setObjectName("Client_listWidget")
        self.verticalLayout.addWidget(self.Client_listWidget)
        self.ClientlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ClientlineEdit.setObjectName("ClientlineEdit")
        self.verticalLayout.addWidget(self.ClientlineEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.peopleSpinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.peopleSpinBox.setObjectName("peopleSpinBox")
        self.verticalLayout_4.addWidget(self.peopleSpinBox)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.Hotels_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Hotels_comboBox.setObjectName("Hotels_comboBox")
        self.verticalLayout_4.addWidget(self.Hotels_comboBox)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.paymentComboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.paymentComboBox.setObjectName("paymentComboBox")
        self.paymentComboBox.addItem("")
        self.paymentComboBox.addItem("")
        self.verticalLayout_4.addWidget(self.paymentComboBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 5)
        self.add_reservation_pushButton = QtWidgets.QPushButton(self.reservationTab)
        self.add_reservation_pushButton.setGeometry(QtCore.QRect(320, 530, 151, 32))
        self.add_reservation_pushButton.setObjectName("add_reservation_pushButton")
        self.tabWidget.addTab(self.reservationTab, "")
        self.clientsTab = QtWidgets.QWidget()
        self.clientsTab.setObjectName("clientsTab")
        self.widget = QtWidgets.QWidget(self.clientsTab)
        self.widget.setGeometry(QtCore.QRect(215, 0, 401, 528))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.FirstNameInput = QtWidgets.QLineEdit(self.widget)
        self.FirstNameInput.setStyleSheet("")
        self.FirstNameInput.setObjectName("FirstNameInput")
        self.gridLayout.addWidget(self.FirstNameInput, 4, 0, 1, 1)
        self.PhoneNumberLabel = QtWidgets.QLabel(self.widget)
        self.PhoneNumberLabel.setObjectName("PhoneNumberLabel")
        self.gridLayout.addWidget(self.PhoneNumberLabel, 1, 0, 1, 1)
        self.EmailInput = QtWidgets.QLineEdit(self.widget)
        self.EmailInput.setStyleSheet("")
        self.EmailInput.setObjectName("EmailInput")
        self.gridLayout.addWidget(self.EmailInput, 8, 0, 1, 1)
        self.LastNameInput = QtWidgets.QLineEdit(self.widget)
        self.LastNameInput.setStyleSheet("")
        self.LastNameInput.setObjectName("LastNameInput")
        self.gridLayout.addWidget(self.LastNameInput, 6, 0, 1, 1)
        self.PhoneNumberInput = QtWidgets.QLineEdit(self.widget)
        self.PhoneNumberInput.setStyleSheet("")
        self.PhoneNumberInput.setObjectName("PhoneNumberInput")
        self.gridLayout.addWidget(self.PhoneNumberInput, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.LastNameLabel = QtWidgets.QLabel(self.widget)
        self.LastNameLabel.setObjectName("LastNameLabel")
        self.gridLayout.addWidget(self.LastNameLabel, 5, 0, 1, 1)
        self.labelWidget = QtWidgets.QWidget(self.widget)
        self.labelWidget.setStyleSheet("background-color: rgb(18, 65, 141);")
        self.labelWidget.setObjectName("labelWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.labelWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.client_label = QtWidgets.QLabel(self.labelWidget)
        self.client_label.setStyleSheet("color: rgb(243, 249, 254);")
        self.client_label.setObjectName("client_label")
        self.horizontalLayout_3.addWidget(self.client_label)
        self.gridLayout.addWidget(self.labelWidget, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.add_Client_button = QtWidgets.QPushButton(self.widget)
        self.add_Client_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_Client_button.sizePolicy().hasHeightForWidth())
        self.add_Client_button.setSizePolicy(sizePolicy)
        self.add_Client_button.setMinimumSize(QtCore.QSize(200, 25))
        self.add_Client_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.add_Client_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_Client_button.setStyleSheet("")
        self.add_Client_button.setObjectName("add_Client_button")
        self.horizontalLayout_4.addWidget(self.add_Client_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 10, 0, 1, 1)
        self.FirstNameLabel = QtWidgets.QLabel(self.widget)
        self.FirstNameLabel.setObjectName("FirstNameLabel")
        self.gridLayout.addWidget(self.FirstNameLabel, 3, 0, 1, 1)
        self.EmailLabel = QtWidgets.QLabel(self.widget)
        self.EmailLabel.setStyleSheet("")
        self.EmailLabel.setObjectName("EmailLabel")
        self.gridLayout.addWidget(self.EmailLabel, 7, 0, 1, 1)
        self.tabWidget.addTab(self.clientsTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(18, 65, 141);\n"
"    border-radius: 6px;\n"
"    alternate-background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"    color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(18, 65, 141);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout1 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.group_selection_layout = QtWidgets.QHBoxLayout()
        self.group_selection_layout.setObjectName("group_selection_layout")
        self.group_label = QtWidgets.QLabel(self.tab_3)
        self.group_label.setObjectName("group_label")
        self.group_selection_layout.addWidget(self.group_label)
        self.groupComboBox = QtWidgets.QComboBox(self.tab_3)
        self.groupComboBox.setObjectName("groupComboBox")
        self.group_selection_layout.addWidget(self.groupComboBox)
        self.verticalLayout1.addLayout(self.group_selection_layout)
        self.groupPaymentsTable = QtWidgets.QTableWidget(self.tab_3)
        self.groupPaymentsTable.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"\n"
"")
        self.groupPaymentsTable.setObjectName("groupPaymentsTable")
        self.groupPaymentsTable.setColumnCount(5)
        self.groupPaymentsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.groupPaymentsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.groupPaymentsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.groupPaymentsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.groupPaymentsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.groupPaymentsTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout1.addWidget(self.groupPaymentsTable)
        self.paymentFormLayout = QtWidgets.QFormLayout()
        self.paymentFormLayout.setObjectName("paymentFormLayout")
        self.labelDate = QtWidgets.QLabel(self.tab_3)
        self.labelDate.setObjectName("labelDate")
        self.paymentFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelDate)
        self.paymentDateEdit = QtWidgets.QDateEdit(self.tab_3)
        self.paymentDateEdit.setCalendarPopup(True)
        self.paymentDateEdit.setObjectName("paymentDateEdit")
        self.paymentFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.paymentDateEdit)
        self.labelType = QtWidgets.QLabel(self.tab_3)
        self.labelType.setObjectName("labelType")
        self.paymentFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelType)
        self.paymentTypeComboBox = QtWidgets.QComboBox(self.tab_3)
        self.paymentTypeComboBox.setObjectName("paymentTypeComboBox")
        self.paymentTypeComboBox.addItem("")
        self.paymentTypeComboBox.addItem("")
        self.paymentTypeComboBox.addItem("")
        self.paymentFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.paymentTypeComboBox)
        self.labelAmount = QtWidgets.QLabel(self.tab_3)
        self.labelAmount.setObjectName("labelAmount")
        self.paymentFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelAmount)
        self.paymentAmountSpinBox = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.paymentAmountSpinBox.setDecimals(2)
        self.paymentAmountSpinBox.setMaximum(10000.0)
        self.paymentAmountSpinBox.setObjectName("paymentAmountSpinBox")
        self.paymentFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.paymentAmountSpinBox)
        self.verticalLayout1.addLayout(self.paymentFormLayout)
        self.horizontalPaymentButtons = QtWidgets.QHBoxLayout()
        self.horizontalPaymentButtons.setObjectName("horizontalPaymentButtons")
        self.addPaymentButton = QtWidgets.QPushButton(self.tab_3)
        self.addPaymentButton.setObjectName("addPaymentButton")
        self.horizontalPaymentButtons.addWidget(self.addPaymentButton)
        self.deletePaymentButton = QtWidgets.QPushButton(self.tab_3)
        self.deletePaymentButton.setObjectName("deletePaymentButton")
        self.horizontalPaymentButtons.addWidget(self.deletePaymentButton)
        self.editPaymentButton = QtWidgets.QPushButton(self.tab_3)
        self.editPaymentButton.setObjectName("editPaymentButton")
        self.horizontalPaymentButtons.addWidget(self.editPaymentButton)
        self.verticalLayout1.addLayout(self.horizontalPaymentButtons)
        self.paymentStatusLabel = QtWidgets.QLabel(self.tab_3)
        self.paymentStatusLabel.setStyleSheet("font-weight: bold; padding-top: 10px;")
        self.paymentStatusLabel.setObjectName("paymentStatusLabel")
        self.verticalLayout1.addWidget(self.paymentStatusLabel)
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tourslabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tours</p></body></html>"))
        self.Clientlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">client</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "number of people"))
        self.label_4.setText(_translate("MainWindow", "hotel"))
        self.label_5.setText(_translate("MainWindow", "payment type"))
        self.paymentComboBox.setItemText(0, _translate("MainWindow", "card"))
        self.paymentComboBox.setItemText(1, _translate("MainWindow", "cash"))
        self.add_reservation_pushButton.setText(_translate("MainWindow", "Make Reservation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reservationTab), _translate("MainWindow", "Reservation"))
        self.PhoneNumberLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Phone Number</span></p></body></html>"))
        self.LastNameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Last name</span></p></body></html>"))
        self.client_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Clients Register</span></p></body></html>"))
        self.add_Client_button.setText(_translate("MainWindow", "Register"))
        self.FirstNameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">First Name</span></p></body></html>"))
        self.EmailLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Email</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clientsTab), _translate("MainWindow", "Clients"))
        self.group_label.setText(_translate("MainWindow", "Choose Reservation/ Group:"))
        item = self.groupPaymentsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.groupPaymentsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "group_id"))
        item = self.groupPaymentsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "payment_date"))
        item = self.groupPaymentsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "amount"))
        item = self.groupPaymentsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "type"))
        self.labelDate.setText(_translate("MainWindow", "Date of Payment"))
        self.labelType.setText(_translate("MainWindow", "Type of Payment"))
        self.paymentTypeComboBox.setItemText(0, _translate("MainWindow", "Prepayment"))
        self.paymentTypeComboBox.setItemText(1, _translate("MainWindow", "Ιnstallment"))
        self.paymentTypeComboBox.setItemText(2, _translate("MainWindow", "Final Payment"))
        self.labelAmount.setText(_translate("MainWindow", "Amount Payed"))
        self.paymentAmountSpinBox.setPrefix(_translate("MainWindow", "€ "))
        self.addPaymentButton.setText(_translate("MainWindow", "Add Payment"))
        self.deletePaymentButton.setText(_translate("MainWindow", "Delete Payment"))
        self.editPaymentButton.setText(_translate("MainWindow", "Edit Payment"))
        self.paymentStatusLabel.setText(_translate("MainWindow", "Καταβληθέν: 0 / 0 € | Κατάσταση: Unpaid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Group Payments"))
