# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/user/Downloads/GitHubProjects/telo2/ui/reservation.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 665)
        MainWindow.setStyleSheet("QWidget{\n"
"background-color: rgb(243, 249, 254);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color: rgb(18, 65, 141);\n"
"font-size:16px;\n"
"padding-bottom: 0px;\n"
"text-align: center;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid; \n"
"border-radius: 6px; \n"
"border-color:rgb(18, 65, 141);\n"
"padding: 8px;\n"
"color: rgb(18, 65, 141);\n"
"font-size:14px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#fff;\n"
"border: 0px;\n"
"font-size: 16px;\n"
"padding: 5px;\n"
"background-color: rgb(18, 65, 141);\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(47, 142, 228);\n"
"}\n"
"QListWidget {\n"
"    background-color: white;\n"
"    border: 2px solid rgb(18, 65, 141);\n"
"    border-radius: 6px;\n"
"    alternate-background-color: #f0f0f0;\n"
"    padding: 2px;\n"
"    font-size: 14px;\n"
"    color: rgb(18, 65, 141);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 6px;\n"
"    border-bottom: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(18, 65, 141);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.reservationTab = QtWidgets.QWidget()
        self.reservationTab.setObjectName("reservationTab")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.reservationTab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(122, 49, 531, 451))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Tourslabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Tourslabel.setObjectName("Tourslabel")
        self.verticalLayout_2.addWidget(self.Tourslabel)
        self.Tour_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.Tour_listWidget.setObjectName("Tour_listWidget")
        self.verticalLayout_2.addWidget(self.Tour_listWidget)
        self.TourslineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.TourslineEdit.setObjectName("TourslineEdit")
        self.verticalLayout_2.addWidget(self.TourslineEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Clientlabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Clientlabel.setObjectName("Clientlabel")
        self.verticalLayout.addWidget(self.Clientlabel)
        self.Client_listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.Client_listWidget.setStyleSheet("QListWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    alternate-background-color: #f0f0f0;\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #0078d7;  /* Μπλε highlight */\n"
"    color: white;\n"
"}")
        self.Client_listWidget.setObjectName("Client_listWidget")
        self.verticalLayout.addWidget(self.Client_listWidget)
        self.ClientlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.ClientlineEdit.setObjectName("ClientlineEdit")
        self.verticalLayout.addWidget(self.ClientlineEdit)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_4.addWidget(self.spinBox)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.Hotels_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.Hotels_comboBox.setObjectName("Hotels_comboBox")
        self.verticalLayout_4.addWidget(self.Hotels_comboBox)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 5)
        self.tabWidget.addTab(self.reservationTab, "")
        self.clientsTab = QtWidgets.QWidget()
        self.clientsTab.setObjectName("clientsTab")
        self.widget = QtWidgets.QWidget(self.clientsTab)
        self.widget.setGeometry(QtCore.QRect(215, 0, 401, 528))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.FirstNameInput = QtWidgets.QLineEdit(self.widget)
        self.FirstNameInput.setStyleSheet("")
        self.FirstNameInput.setObjectName("FirstNameInput")
        self.gridLayout.addWidget(self.FirstNameInput, 4, 0, 1, 1)
        self.PhoneNumberLabel = QtWidgets.QLabel(self.widget)
        self.PhoneNumberLabel.setObjectName("PhoneNumberLabel")
        self.gridLayout.addWidget(self.PhoneNumberLabel, 1, 0, 1, 1)
        self.EmailInput = QtWidgets.QLineEdit(self.widget)
        self.EmailInput.setStyleSheet("")
        self.EmailInput.setObjectName("EmailInput")
        self.gridLayout.addWidget(self.EmailInput, 8, 0, 1, 1)
        self.LastNameInput = QtWidgets.QLineEdit(self.widget)
        self.LastNameInput.setStyleSheet("")
        self.LastNameInput.setObjectName("LastNameInput")
        self.gridLayout.addWidget(self.LastNameInput, 6, 0, 1, 1)
        self.PhoneNumberInput = QtWidgets.QLineEdit(self.widget)
        self.PhoneNumberInput.setStyleSheet("")
        self.PhoneNumberInput.setObjectName("PhoneNumberInput")
        self.gridLayout.addWidget(self.PhoneNumberInput, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 9, 0, 1, 1)
        self.LastNameLabel = QtWidgets.QLabel(self.widget)
        self.LastNameLabel.setObjectName("LastNameLabel")
        self.gridLayout.addWidget(self.LastNameLabel, 5, 0, 1, 1)
        self.labelWidget = QtWidgets.QWidget(self.widget)
        self.labelWidget.setStyleSheet("background-color: rgb(18, 65, 141);")
        self.labelWidget.setObjectName("labelWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.labelWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.client_label = QtWidgets.QLabel(self.labelWidget)
        self.client_label.setStyleSheet("color: rgb(243, 249, 254);")
        self.client_label.setObjectName("client_label")
        self.horizontalLayout_3.addWidget(self.client_label)
        self.gridLayout.addWidget(self.labelWidget, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.add_Client_button = QtWidgets.QPushButton(self.widget)
        self.add_Client_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_Client_button.sizePolicy().hasHeightForWidth())
        self.add_Client_button.setSizePolicy(sizePolicy)
        self.add_Client_button.setMinimumSize(QtCore.QSize(200, 25))
        self.add_Client_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.add_Client_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_Client_button.setStyleSheet("")
        self.add_Client_button.setObjectName("add_Client_button")
        self.horizontalLayout_4.addWidget(self.add_Client_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 10, 0, 1, 1)
        self.FirstNameLabel = QtWidgets.QLabel(self.widget)
        self.FirstNameLabel.setObjectName("FirstNameLabel")
        self.gridLayout.addWidget(self.FirstNameLabel, 3, 0, 1, 1)
        self.EmailLabel = QtWidgets.QLabel(self.widget)
        self.EmailLabel.setStyleSheet("")
        self.EmailLabel.setObjectName("EmailLabel")
        self.gridLayout.addWidget(self.EmailLabel, 7, 0, 1, 1)
        self.tabWidget.addTab(self.clientsTab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tourslabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Tours</p></body></html>"))
        self.Clientlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">client</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "number of people"))
        self.label_4.setText(_translate("MainWindow", "hotel"))
        self.label_5.setText(_translate("MainWindow", "payment type"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "card"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "cash"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.reservationTab), _translate("MainWindow", "Reservation"))
        self.PhoneNumberLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Phone Number</span></p></body></html>"))
        self.LastNameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Last name</span></p></body></html>"))
        self.client_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Clients Register</span></p></body></html>"))
        self.add_Client_button.setText(_translate("MainWindow", "Register"))
        self.FirstNameLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">First Name</span></p></body></html>"))
        self.EmailLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Email</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.clientsTab), _translate("MainWindow", "Clients"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Page"))
